// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv47ALdxN5hmHt-y4yILKySGuZhHUIP_4',
    appId: '1:686988990733:web:b332ccb155dda81dfd7844',
    messagingSenderId: '686988990733',
    projectId: 'jobly-3dd32',
    authDomain: 'jobly-3dd32.firebaseapp.com',
    storageBucket: 'jobly-3dd32.firebasestorage.app',
    measurementId: 'G-H1W7YC9KQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWJGhmA4REn23Emsm-iy43-h75YpDtzk',
    appId: '1:686988990733:android:fc2025c8f23b70eafd7844',
    messagingSenderId: '686988990733',
    projectId: 'jobly-3dd32',
    storageBucket: 'jobly-3dd32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt5fRNLXxvQnMxmhtmH4vcXb_1BYmYZs8',
    appId: '1:686988990733:ios:f05a976388d3c57ffd7844',
    messagingSenderId: '686988990733',
    projectId: 'jobly-3dd32',
    storageBucket: 'jobly-3dd32.firebasestorage.app',
    iosBundleId: 'com.example.jobly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt5fRNLXxvQnMxmhtmH4vcXb_1BYmYZs8',
    appId: '1:686988990733:ios:f05a976388d3c57ffd7844',
    messagingSenderId: '686988990733',
    projectId: 'jobly-3dd32',
    storageBucket: 'jobly-3dd32.firebasestorage.app',
    iosBundleId: 'com.example.jobly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv47ALdxN5hmHt-y4yILKySGuZhHUIP_4',
    appId: '1:686988990733:web:6a787aeb8f0fdb1efd7844',
    messagingSenderId: '686988990733',
    projectId: 'jobly-3dd32',
    authDomain: 'jobly-3dd32.firebaseapp.com',
    storageBucket: 'jobly-3dd32.firebasestorage.app',
    measurementId: 'G-8Z3KKF8VSZ',
  );

}